ALTER TABLE buyers ADD COLUMN IF NOT EXISTS price NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE buyers ADD COLUMN IF NOT EXISTS contact TEXT;
ALTER TABLE buyers ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE buyers ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'Tempahan';
