ALTER TABLE health_records ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE health_records ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE health_records ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE health_records ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE health_records ADD COLUMN IF NOT EXISTS date DATE;
