ALTER TABLE pets ADD COLUMN IF NOT EXISTS health_status TEXT NOT NULL DEFAULT 'Sihat';
ALTER TABLE pets ADD COLUMN IF NOT EXISTS breed TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS dob DATE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS weight NUMERIC;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS feather_colour TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS posture_class TEXT;
